name: Add new pull requests to project board

on:
  pull_request:
    types:
      - opened

jobs:
  add_pull_request_to_project:
    runs-on: ubuntu-latest
    steps:
      - uses: itchysats/actions/add-project-item@main
        with:
          board_id: ${{ secrets.PROJECT_BOARD_ID }}
          item_id: ${{ github.event.pull_request.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.ITCHY_PROJECT_AUTOMATION_TOKEN }}
